// Generated by https://quicktype.io

export interface AssetsData {
  status: Status;
  details: Details;
  offers: any[];
  events: any[];
  listing?: Listing;
  collection?: Collection;
}

export interface Collection {
  policy_id: string;
}

export interface Details {
  mintOrBurnCount: number;
  assetName: string;
  metadata: Listing;
  readableAssetName: string;
  quantity: number;
  onchainMetadata: OnchainMetadata;
  initialMintTxHash: string;
  fingerprint: string;
  asset: string;
  policyId: string;
}

export interface Listing {}

export interface OnchainMetadata {
  image?: string;
  name?: string;
  mediaType?: string;
  description?: string;
  files?: any;
  category?: string;
  royaltiesWallet1?: string;
  profileCollectionImg?: string;
  wallpaperCollectionImg?: string;
  collection?: string;
  royaltiesWallet2?: string;
  authors?: string;
  organization?: string;
  mintedBy?: string;
}

export interface Status {
  locked: boolean;
  contractVersion?: string;
  submittedBy?: string;
  datum?: Datum;
  submittedOn?: number;
  artistAddress?: string;
  datumHash?: string;
  txHash?: string;
}

export interface Datum {
  price: number;
  sa: string;
  tn: string;
  ra: string;
  rp: number;
  cs: string;
}
